version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  webserver:
    image: puckel/docker-airflow:1.10.9
    build:
      context: https://github.com/puckel/docker-airflow.git#1.10.9
      dockerfile: Dockerfile
      args:
        PYTHON_DEPS: sqlalchemy==1.3.0 markupsafe==2.0.1 wtforms==2.2 azure-storage-blob==12.14.1 azure-cosmos==4.0.0 requests~=2.23.0
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=S13e9NGOO9twOYbP_JIhNFn1YDLZ9m3ep8F7RlqNGbk=
      - AIRFLOW__WEBSERVER__WORKERS=8
      - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/isr/dags
      - ADOBE_API_KEY=${ADOBE_API_KEY}
      - ADOBE_PRODUCT=${ADOBE_PRODUCT}
      - ADOBE_CONTAINER_NAME=${ADOBE_CONTAINER_NAME}
      - AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
    volumes:
      - ./isr:/usr/local/airflow/isr
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3